### ISSUE TITLE
Site. v1.1: primitive page

### ISSUE THREAD

**Issue by derfex** [univt/student#10]
# Структура

1. Лого
2. Девиз
3. Как мы делаем работы
4. Что мы делаем
5. Мы не биржа. Строчка о том, что мы не биржа и все работники профессионалы и работают от лица компании.
6. Прайс (карточки)
7. Отзывы (карточки)
8. Наши особенности (карточки)
9. Часто задаваемые вопросы
10. Контакты

- [x] Лого
- [x] Девиз
- [x] Прайс (карточки)
- [x] Часто задаваемые вопросы
- [x] Контакты

# Доработки

## Price list

- [x] Переименовать в «Дипломная работа».
- [x] Добавить на карточку услуги кнопку (ссылку) ("открыть чат"), ведущую на https://vk.com/im?sel=-222131889.
- [x] Обновить список услуг на актуальный.

### Актуальный список

- Курсовая работа от 2700
- Реферат от 600
- Дипломная работа от 6000
- Сессия под ключ от 3000
- Отчёт по практике от 2000
- Эссе от 400
- Презентация от 400
- Расчётно-графическая работа (РГР) от 800
- Повышение оригинальности от 400
- Помощь с тестом от 400
- Другое — по договорённости

## Часто задаваемые вопросы

- [x] Разрешать только один открытый вопрос.
- [x] По умолчанию все элементы свёрнуты.

## Контакты

- [x] Сделать ссылку на VK первой (слева)

**Comment by laffleur** [comment]
Дипломная работа
Отчет по практике от 2000
Сворачиваемость "часто задаваемые вопросы"

1. Курсовая работа от 2700
2. Реферат от 600
3. Дипломная работа от 6000
4. Сессия под ключ от 3000
5. Эссе от 400
6. Презентация от 400
7. РГР от 800
8. Повышение оригинальности от 400
9. Помощь с тестом от 400
10. Другое

Сделать ссылку на вк первой (слева)

**### СТРУКТУРА**

Лого
Девиз
Как мы делаем работы
Что мы делаем
Мы не биржа
Прайс (карточки)
Отзывы (карточки)
Наши особенности (карточки)
Часто задаваемые вопросы
Контакты


![image](https://github.com/user-attachments/assets/50d421d2-ed9f-4514-9dbc-87c2246543c4)

![изображение_2024-07-26_193737521](https://github.com/user-attachments/assets/bc3c38b5-106f-42c5-9267-f2a87a995705)

**Comment by laffleur** [comment]
ДЕВИЗ

мы верим, что можем изменить образование, чтобы оно стало удобнее и легче

**Comment by laffleur** [comment]
> # Структура
> 1. Лого
> 2. Девиз
> 3. Как мы делаем работы

Как мы делаем?
Мы внимательно изучаем ваши требования и ожидания, чтобы точно понять, что вам нужно. Каждый заказ анализируется с учетом всех деталей, чтобы обеспечить максимальную точность и соответствие.
В нашей команде работают профессионалы с обширным опытом и глубокими знаниями в различных областях. Мы тщательно подбираем автора, который идеально подходит для выполнения вашей работы.
Наши эксперты проводят всестороннее исследование, используя надежные источники и современные методы анализа. Это позволяет нам создавать работы, которые не только информативны, но и отражают последние достижения в соответствующей области.
После написания работа проходит несколько этапов проверки на соответствие требованиям, грамматическую и стилистическую корректность. Мы используем современные системы для проверки уникальности, чтобы гарантировать оригинальность каждой работы.
Мы ценим ваше мнение и всегда готовы внести необходимые корректировки, чтобы полностью удовлетворить ваши ожидания. Ваша удовлетворенность — наш приоритет.


> 4. Что мы делаем

Что мы делаем?

Эссе и рефераты: Краткие и содержательные работы, которые помогут вам выразить свои мысли и идеи.
Курсовые работы: Глубокие исследования по заданным темам с детальным анализом и обоснованием.
Дипломные и магистерские работы: Комплексные проекты, включающие оригинальные исследования и предложения.
Научные статьи и отчеты: Публикации, которые соответствуют высоким академическим стандартам.
Презентации и проекты: Визуальные и содержательные работы для успешной защиты ваших идей.


> 5. Мы не биржа. Строчка о том, что мы не биржа и все работники профессионалы и работают от лица компании.
> 6. Прайс (карточки)
> 7. Отзывы (карточки)
> 8. Наши особенности (карточки)
Наши особенности
Индивидуальный подход: Каждый заказ уникален, и мы подходим к каждому клиенту с учетом его индивидуальных потребностей и предпочтений.
Профессионализм и опыт: В нашей команде работают специалисты с высоким уровнем квалификации и многолетним опытом в различных академических областях.
Оперативность и пунктуальность: Мы строго соблюдаем сроки выполнения заказов и гарантируем их своевременную отправку.
Конфиденциальность: Мы обеспечиваем полную конфиденциальность и безопасность ваших данных.
Гарантия качества: Мы стремимся к совершенству и готовы внести любые изменения, чтобы обеспечить ваше полное удовлетворение нашей работой.


> 9. Часто задаваемые вопросы
> 10. Контакты
> 
> * [ ]  Лого
> * [ ]  Девиз
> * [ ]  Прайс (карточки)
> * [ ]  Часто задаваемые вопросы
> * [ ]  Контакты
> 
> # Доработки
> ## Price list
> * [ ]  Переименовать в "Дипломная работа".
> * [ ]  Добавить на карточку услуги кнопку (ссылку) ("открыть чат"), ведущую на https://vk.com/im?sel=-222131889
> 
> ### Актуальный список
> * Курсовая работа от 2700
> * Реферат от 600
> * Дипломная работа от 6000
> * Сессия под ключ от 3000
> * Отчёт по практике от 2000
> * Эссе от 400
> * Презентация от 400
> * Расчётно-графическая работа (РГР) от 800
> * Повышение оригинальности от 400
> * Помощь с тестом от 400
> * Другое — по договорённости
> 
> ## Часто задаваемые вопросы
> * [ ]  Разрешать только один открытый вопрос.
> * [ ]  По умолчанию все элементы свёрнуты.
> 
> ## Контакты
> * [ ]  Сделать ссылку на VK первой (слева)
